#pragma config(Motor,  port1,           bigMotor1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           smolMotor1,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           bigMotor2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          smolMotor2,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		motor[port1] = motor[port2] = motor[port9] = motor[port10] = 127;
		delay(3000);

		motor[port1] = motor[port2] = motor[port9] = motor[port10] = 0;
		delay(1000);

		motor[port1] = motor[port2] = motor[port9] = motor[port10] = -127;
		delay(3000);

		motor[port1] = motor[port2] = motor[port9] = motor[port10] = 0;
		delay(1000);
	}

}
